# Generated by Django 6.1.2 on 2026-10-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Paciente')),
                ('prioridade', models.CharField(choices=[('normal', 'Normal'), ('preferencial', 'Preferencial')], default='normal', max_length=20, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando Atendimento'), ('chamado', 'Chamado para Atendimento'), ('finalizado', 'Atendimento Finalizado'), ('cancelado', 'Cancelado / Desistência')], default='aguardando', max_length=20, verbose_name='Status')),
                ('sala', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sala / Consultório')),
                ('medico', models.CharField(blank=True, max_length=120, null=True, verbose_name='Médico Responsável')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Horário de Chegada')),
                ('chamado_em', models.DateTimeField(blank=True, null=True, verbose_name='Momento da Chamada')),
                ('finalizado_em', models.DateTimeField(blank=True, null=True, verbose_name='Momento de Finalização')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['criado_em'],
            },
        ),
    ]
